// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuGpwQk0PWyqOYC2DFv5J4alsfVPt-uq0',
    appId: '1:116948528623:web:f7796c346998970c7b5a1a',
    messagingSenderId: '116948528623',
    projectId: 'bitirmeprojesiaydnsmt',
    authDomain: 'bitirmeprojesiaydnsmt.firebaseapp.com',
    databaseURL:
        'https://bitirmeprojesiaydnsmt-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bitirmeprojesiaydnsmt.appspot.com',
    measurementId: 'G-3NV4GFRD70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCliDv7f8l8oQ1SwaJXxt-7IjkODsZHkw',
    appId: '1:116948528623:android:56eb09aa9d004eaf7b5a1a',
    messagingSenderId: '116948528623',
    projectId: 'bitirmeprojesiaydnsmt',
    databaseURL:
        'https://bitirmeprojesiaydnsmt-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bitirmeprojesiaydnsmt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH6d0t_HG6DbWsjKcqNkh6UGMyxW4PVB4',
    appId: '1:116948528623:ios:6c1dfd7f6f8ab1607b5a1a',
    messagingSenderId: '116948528623',
    projectId: 'bitirmeprojesiaydnsmt',
    databaseURL:
        'https://bitirmeprojesiaydnsmt-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bitirmeprojesiaydnsmt.appspot.com',
    iosClientId:
        '116948528623-3milvagm5o6p48f27tnj53vj81t0rqis.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSametAydin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH6d0t_HG6DbWsjKcqNkh6UGMyxW4PVB4',
    appId: '1:116948528623:ios:6c1dfd7f6f8ab1607b5a1a',
    messagingSenderId: '116948528623',
    projectId: 'bitirmeprojesiaydnsmt',
    databaseURL:
        'https://bitirmeprojesiaydnsmt-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bitirmeprojesiaydnsmt.appspot.com',
    iosClientId:
        '116948528623-3milvagm5o6p48f27tnj53vj81t0rqis.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSametAydin',
  );
}
